spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

minio:
  access-key: jAaiKMujJdc2Zxn4Trpv
  secret-key: qy6kbwYDNIwbfBr459bcHxXcoJSvySSxaAASJxA1
#  access-key: colasoft001
#  secret-key: JIm3p5yuc7
  endpoint: http://192.168.1.20:9001
  bucket-name: dev   # 登陆minio创建的文件桶

server:
  port: 9091